#datasouce
spring:
    datasource:
      url: jdbc:mysql://${mysql:127.0.0.1}:3306/springboot?useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
management:
  security:
    enabled: false